# Site settings
title:       Stanley Semilla
email:       semillastan@gmail.com
author:      Stanley Semilla
description: "The awesome life of Stanley"
baseurl:     "http://semillastan.github.io"
url:         "http://semillastan.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
facebook_username: semillastan
github_username: semillastan
stackoverflow_id: semillastan
twitter_username: semillastan
google_plus_id: semillastan
linkedin_username: semillastan
angellist_username:
medium_id: semillastan
bitcoin_url: 352Yvz9uZDYugNnCXz6YJwL2QjUASmBxda
paypal_url: semillastan@gmail.com
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
